### ISSUE TITLE
Game crash upon disconnecting/exiting the game

### ISSUE THREAD

**Issue by MKhayle** [Caraxi/RemindMe#14]
The game crashes when trying to disconnect or when exiting the game while RemindMe is enabled.

Sadly, nothing about it is stored in Dalamud.log when it happens. 

I didn't enable a lot of options, here is my json (turned into .txt so that GitHub allows me to upload it) for further testing.
[RemindMe.json in txt form](https://github.com/Caraxi/RemindMe/files/6248176/RemindMe.txt)

**Comment by Caraxi** [comment]
Hopefully this is fixed as of 1.0.5.4, but I'm not sure. Please let me know if you have any more issues with it

**Comment by MKhayle** [comment]
Looks fine, thanks ! I can use it again now.
