### ISSUE TITLE
Tracking Personal Buffs (MNK)

### ISSUE THREAD

**Issue by sumphatguy** [Caraxi/RemindMe#15]
I am trying to figure out if there is a way to track the actual personal buffs that are on me when playing MNK. In particular, I'm looking to track the Twin Snakes buff, Leaden Fist, and Riddle of Earth (and True North, if possible as well). I can only see ways to track the skills cooldown, which is not quite what I'm looking for.

Essentially, I'm looking for a way to isolate key buffs that I need to know whether or not they're active without having to search through the long list of buffs the game currently shows.

**Comment by Caraxi** [comment]
Added Twin Snakes, Leaden Fist, and Riddle of Earth in e197ca28baa6488e7000a9af1beebb4453c0226a
Added True North in bbd83d6b6ba2e877049de33c4221aa902afb0cc7
