### ISSUE TITLE
Icons Missing

### ISSUE THREAD

**Issue by MuttMeat** [Caraxi/RemindMe#16]
Since the update to 5.5, icons no longer show for me.
![Screenshot](https://user-images.githubusercontent.com/45852667/114879221-484b9180-9e01-11eb-9caa-ef4980ca154a.png)

**Comment by Caraxi** [comment]
🤔 works for me just fine
![image](https://user-images.githubusercontent.com/11886749/115015002-34338d00-9ef2-11eb-94a4-18dcdbc1b599.png)
Not sure what could cause that

**Comment by MuttMeat** [comment]
The issue came to be due to a modpack for icons. 

Solved!
