### ISSUE TITLE
"Hide outside of combat" Display option seems to be active all the time on locked displays

### ISSUE THREAD

**Issue by armsteullion** [Caraxi/RemindMe#17]
Hello,

I have a locked display to with CDs on certain skills and to track DoTs.  

It seems clicking the "Hide outside of combat" display option just hides locked display permanently, and toggling this off makes them appear again. 

Clip here: https://www.youtube.com/watch?v=AmrixY5eBFQ

**Comment by Caraxi** [comment]
Fixed in 1.0.5.3 :)
