### ISSUE TITLE
MCH Hot Shot and Air Anchor overlap

### ISSUE THREAD

**Issue by Dogtron3030** [Caraxi/RemindMe#23]
Air Anchor replaces Hot Shot at level 76. The two skills are considered separate by RemindMe, leading to unwanted behaviour when trying to track them.

Issue doesn't exist below 76, because Air Anchor is hidden in the cooldown bar when unavailable, but the tracker will try to track both independently in content where it is. Expected behaviour would be for Hot Shot tracking to disable itself in this scenario.

Current workaround is to simply untick Hot Shot when necessary, but it would be helpful if RemindMe dealt with this on its own.

**Comment by unitymind9** [comment]
DRG - High Jump and Jump

**Comment by Caraxi** [comment]
Fixed with 8712191f0f45cce819c5fcc24da8eebc42cd4513
