### ISSUE TITLE
WAR Berserk - Inner Release overlap

### ISSUE THREAD

**Issue by Ranirinn** [Caraxi/RemindMe#24]
### Current issue
Like #23 the Berserk / Inner Release Warrior abilities are considered different, the same happens with the status buff, right now only the Permament Status Effect from Berserk is tracked.

### Possible solution
Consider both skills a same ability and change the id when one is available (either via level or availability of the skill). Only one check for Actions and one to track the Buff should be enough and ideal.

**Comment by Caraxi** [comment]
Fixed with c497a26ef057685ad16a4d59121ee35be47d2d08
