### ISSUE TITLE
Venture reminder incorrect until opening timers window

### ISSUE THREAD

**Issue by Kanarisky** [Caraxi/RemindMe#32]
Upon logging in, the venture reminder is always active, indicating ventures complete. Once the timer window is opened at least once, the venture reminder becomes accurate.

See video below.
The yellow bar underneath chat is my venture reminder. I have just logged in and currently have all my retainers on ventures. Once i open the Timers window, the reminder hides itself, as it should.
https://user-images.githubusercontent.com/68185248/129650447-14c4a20b-0b30-4e77-beb8-25943c9141c1.mp4

Additional issue, shown in video:
Venture reminder always displays as you are opening the Timers window, for a split second. Not a big deal but worth pointing out in case it is an easy fix.

**Comment by Caraxi** [comment]
if you enable text it will tell you why it is showing until the window is open. there is no way to know the current timers until the client knows itself
