### ISSUE TITLE
Warrior missing Inner Release and Nascent Flash

### ISSUE THREAD

**Issue by xiaoai903** [Caraxi/RemindMe#33]
Warrior is missing Inner Release and Nascent Flash. They work similar as Berserk and Raw Intuition. Thanks!

**Comment by Caraxi** [comment]
Inner released added 50d6a2d02103d158ea495d2b02ad8f1508540d11
Still need to add Nascent Flash

**Comment by Caraxi** [comment]
Nascent Flash added with 7986168e34084b1917e4a0440e249d8b118d82be
