### ISSUE TITLE
Feature Request: Food buff reminder

### ISSUE THREAD

**Issue by Kanarisky** [Caraxi/RemindMe#38]
A food buff reminder that you could customise to activate when you have less than x number of minutes left on your food buff would be great. It wouldn't be too useful if you could only have it activate once you've lost Well Fed, because that will most likely happen mid-pull.
For example, when I prog I start to consider re-fooding at ~12 minutes remaining on Well Fed.

**Comment by Caraxi** [comment]
Added with b1424fd69a345ac4c4d7b1aed1851d21c5284d5a
