### ISSUE TITLE
"Hide outside of combat" option not detecting combat

### ISSUE THREAD

**Issue by majesstic** [Caraxi/RemindMe#4]
With the "Hide outside of combat" display option selected, my configured cooldown displays never appear regardless of combat state. It seems combat is not being detected?

Steps to replicate:
1. Create a display and add any # of actions
2. Lock display
3. Check "Hide outside of combat" option
4. Enter combat. Display should appear when cooldown conditions are met, but does not.

All displays seem to otherwise work as expected with this option disabled.

Edit: Sorry, I just noticed the commits for 0.0.2.1 include a note about fixing combat detection. Looks like maybe I just need to wait for that update to be pushed. :)

**Comment by Caraxi** [comment]
Yep. Already fixed :) Will be up soon
