### ISSUE TITLE
DRK Plunge timer is 60s rather than 30s

### ISSUE THREAD

**Issue by FakeGodz** [Caraxi/RemindMe#42]
![image](https://user-images.githubusercontent.com/87436803/133949174-61199eb4-61f9-41b6-9904-b72e1464f5c1.png)

![image](https://user-images.githubusercontent.com/87436803/133949203-3335ad54-879b-4582-8737-001fd08dfef9.png)

**Comment by Caraxi** [comment]
Should be fixed as of e274bff9e87484b201d154a6e7beecb320fbda9f
