### ISSUE TITLE
MIssing status effects: Lance Charge(DRG) and Raging Strikes(BRD)

### ISSUE THREAD

**Issue by DenL** [Caraxi/RemindMe#43]
As title. These are simple +dmg cd's. Hoping to have them added to status effects.

**Comment by Caraxi** [comment]
Done with 
0854770ea76f23354337e396dc7c4a336aca53b0 `[BRD] Add Raging Strikes`
7c827541503aab1b29390a0c1da8109396ab2768 `[DRG] Add Lance Charge, Allow Lancer to use DRG status effects`

**Comment by DenL** [comment]
Hello, this is a small thing Lance Charge is not categorized as [SELF] in status effects. So (depending on setup) bar labels would have your own name in it instead of just the buff name. Would be great if it could be fixed. Thanks!
