### ISSUE TITLE
Missing Status effects for Monk

### ISSUE THREAD

**Issue by zedekblue** [Caraxi/RemindMe#7]
First of all I just want to mention there's nowhere I can find this "goat place" discord mentioned to suggest changes. Put a link somewhere?
Second of all, I'd love a reminder for monk to activate Fists of Fire. It's deactivated on level sync similar to tank stance & sect, and would be a great help for the dozens of us who play monk to keep it on.

**Comment by Caraxi** [comment]
goat place is the xivlauncher discord
I've got that panned, just need to actually log into a character with monk so I can implement it at some point. It will be in the next version for sure

**Comment by zedekblue** [comment]
I'll go ahead and close this since it is now implemented.
Thanks!
