### ISSUE TITLE
tank defensive cooldown status effects

### ISSUE THREAD

**Issue by adamkittelson** [Caraxi/RemindMe#9]
It'd be rad if defensive cooldowns (rampart etc etc) for tanks could be added to status effects. It'd be useful to be able to use the next cooldown as they expire for trash packs in dungeons.

If you don't have any objections to the idea I'd be happy to create a PR for this, I would just need to know how to get the job and ability ids.

Thanks!

**Comment by Caraxi** [comment]
No problem with you doing a PR for it :)
If you build in debug mode, the debug tab will tell you the IDs as you use things
